[[redirects]]
  from = "http://docs.openfeature.dev/*"
  to = "https://openfeature.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.openfeature.dev/*"
  to = "https://openfeature.dev/:splat"
  status = 301
  force = true